//! SNP launch measurement verification.
//!
//! Verifies that a kernel command line produced the measurement in an attestation report.
//! Uses a pre-computed intermediate launch digest (covering static components: OVMF, metadata,
//! kernel/initrd hashes) so only the dynamic cmdline part is recomputed.
//!
//! Algorithm (with `kernel-hashes=on`):
//! 1. SHA-256 hashes of kernel, initrd, cmdline are embedded in a SEV_KERNEL_HASHES page
//! 2. This page is measured as a Normal page via SHA-384 GCTX update
//! 3. VMSA pages (per vCPU) are measured via SHA-384 GCTX updates
//! 4. Final launch digest = expected measurement

use anyhow::ensure;
use sha2::{Digest, Sha256, Sha384};

// --- SEV_KERNEL_HASHES page GUIDs (from OVMF/QEMU specification) ---

/// Table GUID: 9438d606-4f22-4cc9-b479-a793d411fd21
const SEV_HASH_TABLE_GUID: [u8; 16] = [
    0x06, 0xd6, 0x38, 0x94, 0x22, 0x4f, 0xc9, 0x4c,
    0xb4, 0x79, 0xa7, 0x93, 0xd4, 0x11, 0xfd, 0x21,
];

/// Cmdline entry GUID: 97d02dd8-bd20-4c94-aa78-e7714d36ab2a
const SEV_CMDLINE_ENTRY_GUID: [u8; 16] = [
    0xd8, 0x2d, 0xd0, 0x97, 0x20, 0xbd, 0x94, 0x4c,
    0xaa, 0x78, 0xe7, 0x71, 0x4d, 0x36, 0xab, 0x2a,
];

/// Initrd entry GUID: b6ed3250-b3e4-4bbe-ac68-1b4c81eb0e64
const SEV_INITRD_ENTRY_GUID: [u8; 16] = [
    0x50, 0x32, 0xed, 0xb6, 0xe4, 0xb3, 0xbe, 0x4b,
    0xac, 0x68, 0x1b, 0x4c, 0x81, 0xeb, 0x0e, 0x64,
];

/// Kernel entry GUID: 4de79437-abd2-427f-b835-d5b172d2045b
const SEV_KERNEL_ENTRY_GUID: [u8; 16] = [
    0x37, 0x94, 0xe7, 0x4d, 0xd2, 0xab, 0x7f, 0x42,
    0xb8, 0x35, 0xd5, 0xb1, 0x72, 0xd2, 0x04, 0x5b,
];

// --- Page types for GCTX update ---
const PAGE_TYPE_NORMAL: u8 = 0x01;
const PAGE_TYPE_VMSA: u8 = 0x02;

/// GPA for VMSA pages (AMD SEV-SNP specification)
const VMSA_GPA: u64 = 0xFFFF_FFFF_F000;

/// Size of a single hash entry: 16 (GUID) + 2 (len) + 32 (SHA-256 hash) = 50
const HASH_ENTRY_SIZE: usize = 50;
/// Size of the hash table header: 16 (GUID) + 2 (len)
const HASH_TABLE_HEADER_SIZE: usize = 18;
/// Total table size: header + 3 entries
const HASH_TABLE_SIZE: usize = HASH_TABLE_HEADER_SIZE + 3 * HASH_ENTRY_SIZE;

/// Pre-computed build constants generated by `snp-digest --checkpoint`.
///
/// These cover the STATIC parts of the measurement that don't change between deployments:
/// - OVMF firmware pages
/// - OVMF metadata sections (SnpSecMemory, SnpSecrets, Cpuid)
/// - Kernel and initrd SHA-256 hashes (same binary per build)
///
/// Only the kernel cmdline varies between deployments (fork_url, fork_block).
#[derive(Debug, Clone)]
pub struct MeasurementConstants {
    /// SHA-384 launch digest state after OVMF pages + metadata sections
    /// (everything except SEV_KERNEL_HASHES page and VMSA pages).
    pub intermediate_ld: [u8; 48],

    /// SHA-256 hash of the kernel binary (pre-computed, constant per build).
    pub kernel_sha256: [u8; 32],

    /// SHA-256 hash of the initrd binary (pre-computed, constant per build).
    pub initrd_sha256: [u8; 32],

    /// Guest physical address of the SEV_KERNEL_HASHES page (from OVMF metadata).
    pub hashes_page_gpa: u64,

    /// Byte offset within the page where the hash table starts.
    /// This is `hashes_page_gpa - section_base_gpa` (typically 0).
    pub hashes_table_offset: usize,

    /// Serialized VMSA page content for each vCPU (4096 bytes each).
    /// For a single vCPU config, this contains one 4096-byte VMSA.
    pub vmsa_pages: Vec<[u8; 4096]>,
}

/// Fork parameters parsed from kernel cmdline.
#[derive(Debug, Clone, Default)]
pub struct ForkParams {
    /// Fork provider URL (e.g., "https://eth-sepolia.g.alchemy.com/v2/...")
    pub fork_url: Option<String>,
    /// Fork block number
    pub fork_block: Option<u64>,
}

/// Verifies that `cmdline` produces the `expected_measurement` from the attestation report.
///
/// This reconstructs the SNP launch measurement from:
/// 1. Pre-computed intermediate state (OVMF + metadata)
/// 2. Dynamic cmdline (hashed via SHA-256)
/// 3. Pre-computed kernel/initrd hashes
/// 4. Pre-computed VMSA pages
pub fn verify_measurement(
    constants: &MeasurementConstants,
    cmdline: &str,
    expected_measurement: &[u8; 48],
) -> anyhow::Result<()> {
    // Step 1: Compute SHA-256 of the cmdline (null-terminated, trimmed)
    let cmdline_hash = compute_cmdline_hash(cmdline);

    // Step 2: Build the SEV_KERNEL_HASHES page
    let hashes_page = build_sev_kernel_hashes_page(
        &cmdline_hash,
        &constants.initrd_sha256,
        &constants.kernel_sha256,
        constants.hashes_table_offset,
    );

    // Step 3: GCTX update with the hashes page (Normal page)
    let mut ld = constants.intermediate_ld;
    gctx_update(&mut ld, &hashes_page, PAGE_TYPE_NORMAL, constants.hashes_page_gpa);

    // Step 4: GCTX update for each VMSA page
    for vmsa_page in &constants.vmsa_pages {
        gctx_update(&mut ld, vmsa_page, PAGE_TYPE_VMSA, VMSA_GPA);
    }

    // Step 5: Compare with expected measurement
    ensure!(
        ld == *expected_measurement,
        "measurement mismatch: computed {}, expected {}",
        hex::encode(ld),
        hex::encode(expected_measurement),
    );

    Ok(())
}

/// Computes SHA-256 of the kernel cmdline (null-terminated, as per OVMF spec).
pub fn compute_cmdline_hash(cmdline: &str) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(cmdline.trim().as_bytes());
    hasher.update(b"\0");
    hasher.finalize().into()
}

/// Builds a 4096-byte SEV_KERNEL_HASHES page.
///
/// Layout:
/// - `offset` bytes of zeros
/// - Hash table: GUID + length + 3 entries (cmdline, initrd, kernel)
/// - Remaining bytes are zero-padded
fn build_sev_kernel_hashes_page(
    cmdline_sha256: &[u8; 32],
    initrd_sha256: &[u8; 32],
    kernel_sha256: &[u8; 32],
    offset: usize,
) -> [u8; 4096] {
    let mut page = [0u8; 4096];
    let mut pos = offset;

    // Table header: GUID + total length
    let table_len = (HASH_TABLE_SIZE) as u16;
    page[pos..pos + 16].copy_from_slice(&SEV_HASH_TABLE_GUID);
    pos += 16;
    page[pos..pos + 2].copy_from_slice(&table_len.to_le_bytes());
    pos += 2;

    // Entry 1: Cmdline
    write_hash_entry(&mut page, &mut pos, &SEV_CMDLINE_ENTRY_GUID, cmdline_sha256);

    // Entry 2: Initrd
    write_hash_entry(&mut page, &mut pos, &SEV_INITRD_ENTRY_GUID, initrd_sha256);

    // Entry 3: Kernel
    write_hash_entry(&mut page, &mut pos, &SEV_KERNEL_ENTRY_GUID, kernel_sha256);

    page
}

/// Writes a single hash entry (GUID + length + SHA-256 hash) into the page.
fn write_hash_entry(page: &mut [u8; 4096], pos: &mut usize, guid: &[u8; 16], hash: &[u8; 32]) {
    page[*pos..*pos + 16].copy_from_slice(guid);
    *pos += 16;
    let entry_len = HASH_ENTRY_SIZE as u16;
    page[*pos..*pos + 2].copy_from_slice(&entry_len.to_le_bytes());
    *pos += 2;
    page[*pos..*pos + 32].copy_from_slice(hash);
    *pos += 32;
}

/// Performs a single GCTX page update: `ld = SHA384(ld || contents || page_metadata)`.
///
/// The page_info buffer (4256 bytes) consists of:
/// - [0..48]:     current launch digest (48 bytes)
/// - [48..4144]:  page contents field (4096 bytes)
/// - [4144..4256]: page metadata (112 bytes)
///
/// For Normal pages: contents = SHA384(page_data) (48 bytes), zero-padded to 4096.
/// For VMSA pages: contents = raw page_data (4096 bytes).
fn gctx_update(ld: &mut [u8; 48], page_contents: &[u8; 4096], page_type: u8, gpa: u64) {
    let mut page_info = [0u8; 4256];

    // Current launch digest
    page_info[0..48].copy_from_slice(ld);

    // Page contents field depends on page type
    if page_type == PAGE_TYPE_NORMAL {
        // Normal pages: SHA-384 hash the page data, place 48-byte digest at [48..96]
        let page_hash = Sha384::digest(page_contents);
        page_info[48..96].copy_from_slice(&page_hash);
        // Rest of [96..4144] stays zero
    } else {
        // VMSA pages: raw 4096-byte content
        page_info[48..4144].copy_from_slice(page_contents);
    }

    // Page metadata (112 bytes at offset 4144)
    // u16 LE: page_info_size = 0x0070 (112)
    page_info[4144] = 0x70;
    page_info[4145] = 0x00;
    // u8: page_type
    page_info[4146] = page_type;
    // u8: is_imi = 0
    page_info[4147] = 0;
    // u8: vmpl3_perms = 0, vmpl2_perms = 0, vmpl1_perms = 0, reserved = 0
    // (already zero from initialization)
    // u64 LE: gpa (at offset 4152)
    page_info[4152..4160].copy_from_slice(&gpa.to_le_bytes());
    // Remaining 96 bytes are zeros (already zero)

    // Compute SHA-384
    let digest = Sha384::digest(&page_info);
    ld.copy_from_slice(&digest);
}

/// Parses fork parameters from a Katana kernel cmdline string.
///
/// Expected format: `console=ttyS0 katana.args=--http.addr,0.0.0.0,...,--fork.provider,URL,--fork.block,123`
pub fn parse_katana_cmdline(cmdline: &str) -> ForkParams {
    let mut params = ForkParams::default();

    // Find katana.args= parameter
    for part in cmdline.split_whitespace() {
        if let Some(args_str) = part.strip_prefix("katana.args=") {
            let args: Vec<&str> = args_str.split(',').collect();
            let mut i = 0;
            while i < args.len() {
                match args[i] {
                    "--fork.provider" => {
                        if i + 1 < args.len() {
                            params.fork_url = Some(args[i + 1].to_string());
                            i += 2;
                            continue;
                        }
                    }
                    "--fork.block" => {
                        if i + 1 < args.len() {
                            params.fork_block = args[i + 1].parse().ok();
                            i += 2;
                            continue;
                        }
                    }
                    _ => {}
                }
                i += 1;
            }
        }
    }

    params
}

/// Computes SHA-256 of a fork URL (for journal output).
pub fn compute_fork_url_hash(url: &str) -> [u8; 32] {
    Sha256::digest(url.as_bytes()).into()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_compute_cmdline_hash() {
        // cmdline is null-terminated and trimmed before hashing
        let hash = compute_cmdline_hash("console=ttyS0");
        // SHA-256("console=ttyS0\0")
        let expected = Sha256::digest(b"console=ttyS0\0");
        assert_eq!(hash, expected.as_slice());
    }

    #[test]
    fn test_compute_cmdline_hash_trimmed() {
        // Trailing whitespace should be trimmed
        let hash1 = compute_cmdline_hash("console=ttyS0");
        let hash2 = compute_cmdline_hash("console=ttyS0  ");
        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_different_cmdlines_produce_different_hashes() {
        let hash1 = compute_cmdline_hash("console=ttyS0 katana.args=--fork.block,100");
        let hash2 = compute_cmdline_hash("console=ttyS0 katana.args=--fork.block,200");
        assert_ne!(hash1, hash2);
    }

    #[test]
    fn test_build_sev_kernel_hashes_page_size() {
        let page = build_sev_kernel_hashes_page(&[0u8; 32], &[0u8; 32], &[0u8; 32], 0);
        assert_eq!(page.len(), 4096);
    }

    #[test]
    fn test_build_sev_kernel_hashes_page_structure() {
        let cmdline_hash = [0xAAu8; 32];
        let initrd_hash = [0xBBu8; 32];
        let kernel_hash = [0xCCu8; 32];

        let page = build_sev_kernel_hashes_page(&cmdline_hash, &initrd_hash, &kernel_hash, 0);

        // Table GUID at offset 0
        assert_eq!(&page[0..16], &SEV_HASH_TABLE_GUID);

        // Table length at offset 16 (u16 LE)
        let table_len = u16::from_le_bytes([page[16], page[17]]);
        assert_eq!(table_len as usize, HASH_TABLE_SIZE);

        // Cmdline entry GUID at offset 18
        assert_eq!(&page[18..34], &SEV_CMDLINE_ENTRY_GUID);
        // Cmdline hash at offset 36
        assert_eq!(&page[36..68], &cmdline_hash);

        // Initrd entry GUID at offset 68
        assert_eq!(&page[68..84], &SEV_INITRD_ENTRY_GUID);
        // Initrd hash at offset 86
        assert_eq!(&page[86..118], &initrd_hash);

        // Kernel entry GUID at offset 118
        assert_eq!(&page[118..134], &SEV_KERNEL_ENTRY_GUID);
        // Kernel hash at offset 136
        assert_eq!(&page[136..168], &kernel_hash);

        // Rest should be zeros
        assert!(page[168..].iter().all(|&b| b == 0));
    }

    #[test]
    fn test_build_sev_kernel_hashes_page_with_offset() {
        let page = build_sev_kernel_hashes_page(&[0xAA; 32], &[0xBB; 32], &[0xCC; 32], 64);

        // First 64 bytes should be zeros
        assert!(page[0..64].iter().all(|&b| b == 0));
        // Table GUID starts at offset 64
        assert_eq!(&page[64..80], &SEV_HASH_TABLE_GUID);
    }

    #[test]
    fn test_gctx_update_deterministic() {
        let mut ld1 = [0u8; 48];
        let mut ld2 = [0u8; 48];
        let page = [0x42u8; 4096];

        gctx_update(&mut ld1, &page, PAGE_TYPE_NORMAL, 0x1000);
        gctx_update(&mut ld2, &page, PAGE_TYPE_NORMAL, 0x1000);

        assert_eq!(ld1, ld2);
    }

    #[test]
    fn test_gctx_update_different_page_types() {
        let mut ld_normal = [0u8; 48];
        let mut ld_vmsa = [0u8; 48];
        let page = [0x42u8; 4096];

        gctx_update(&mut ld_normal, &page, PAGE_TYPE_NORMAL, 0x1000);
        gctx_update(&mut ld_vmsa, &page, PAGE_TYPE_VMSA, 0x1000);

        assert_ne!(ld_normal, ld_vmsa);
    }

    #[test]
    fn test_gctx_update_different_gpa() {
        let mut ld1 = [0u8; 48];
        let mut ld2 = [0u8; 48];
        let page = [0x42u8; 4096];

        gctx_update(&mut ld1, &page, PAGE_TYPE_NORMAL, 0x1000);
        gctx_update(&mut ld2, &page, PAGE_TYPE_NORMAL, 0x2000);

        assert_ne!(ld1, ld2);
    }

    #[test]
    fn test_verify_measurement_end_to_end() {
        // Construct a simple test case:
        // 1. Start with zero intermediate_ld
        // 2. Apply hashes page + 1 VMSA
        // 3. Verify the result matches
        let cmdline = "console=ttyS0 katana.args=--http.addr,0.0.0.0";
        let kernel_sha256 = Sha256::digest(b"fake-kernel").into();
        let initrd_sha256 = Sha256::digest(b"fake-initrd").into();
        let vmsa_page = [0x55u8; 4096];

        let constants = MeasurementConstants {
            intermediate_ld: [0u8; 48],
            kernel_sha256,
            initrd_sha256,
            hashes_page_gpa: 0x800000,
            hashes_table_offset: 0,
            vmsa_pages: vec![vmsa_page],
        };

        // Compute expected measurement manually
        let cmdline_hash = compute_cmdline_hash(cmdline);
        let hashes_page = build_sev_kernel_hashes_page(
            &cmdline_hash,
            &constants.initrd_sha256,
            &constants.kernel_sha256,
            0,
        );
        let mut expected_ld = [0u8; 48];
        gctx_update(&mut expected_ld, &hashes_page, PAGE_TYPE_NORMAL, 0x800000);
        gctx_update(&mut expected_ld, &vmsa_page, PAGE_TYPE_VMSA, VMSA_GPA);

        // Verify should pass
        let result = verify_measurement(&constants, cmdline, &expected_ld);
        assert!(result.is_ok(), "verify_measurement failed: {:?}", result.err());
    }

    #[test]
    fn test_verify_measurement_wrong_cmdline_fails() {
        let kernel_sha256 = [0u8; 32];
        let initrd_sha256 = [0u8; 32];
        let vmsa_page = [0u8; 4096];

        let constants = MeasurementConstants {
            intermediate_ld: [0u8; 48],
            kernel_sha256,
            initrd_sha256,
            hashes_page_gpa: 0x800000,
            hashes_table_offset: 0,
            vmsa_pages: vec![vmsa_page],
        };

        // Compute measurement for cmdline A
        let cmdline_a = "console=ttyS0 katana.args=--fork.block,100";
        let hash_a = compute_cmdline_hash(cmdline_a);
        let page_a = build_sev_kernel_hashes_page(&hash_a, &initrd_sha256, &kernel_sha256, 0);
        let mut measurement_a = [0u8; 48];
        gctx_update(&mut measurement_a, &page_a, PAGE_TYPE_NORMAL, 0x800000);
        gctx_update(&mut measurement_a, &vmsa_page, PAGE_TYPE_VMSA, VMSA_GPA);

        // Verify with cmdline B should fail
        let cmdline_b = "console=ttyS0 katana.args=--fork.block,200";
        let result = verify_measurement(&constants, cmdline_b, &measurement_a);
        assert!(result.is_err(), "should fail with wrong cmdline");
    }

    #[test]
    fn test_parse_katana_cmdline_full() {
        let cmdline = "console=ttyS0 katana.args=--http.addr,0.0.0.0,--http.port,5050,--fork.provider,https://rpc.example.com,--fork.block,5000000,--tee.provider,sev-snp";
        let params = parse_katana_cmdline(cmdline);

        assert_eq!(params.fork_url.as_deref(), Some("https://rpc.example.com"));
        assert_eq!(params.fork_block, Some(5000000));
    }

    #[test]
    fn test_parse_katana_cmdline_no_fork() {
        let cmdline = "console=ttyS0 katana.args=--http.addr,0.0.0.0,--http.port,5050,--tee.provider,sev-snp";
        let params = parse_katana_cmdline(cmdline);

        assert!(params.fork_url.is_none());
        assert!(params.fork_block.is_none());
    }

    #[test]
    fn test_parse_katana_cmdline_no_katana_args() {
        let cmdline = "console=ttyS0 loglevel=7";
        let params = parse_katana_cmdline(cmdline);

        assert!(params.fork_url.is_none());
        assert!(params.fork_block.is_none());
    }

    #[test]
    fn test_fork_url_hash_deterministic() {
        let hash1 = compute_fork_url_hash("https://rpc.example.com");
        let hash2 = compute_fork_url_hash("https://rpc.example.com");
        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_fork_url_hash_different_urls() {
        let hash1 = compute_fork_url_hash("https://rpc.example.com");
        let hash2 = compute_fork_url_hash("https://other.rpc.com");
        assert_ne!(hash1, hash2);
    }
}
