#![no_main]
sp1_zkvm::entrypoint!(main);

use alloy_primitives::{Bytes, B256};
use amd_sev_snp_attestation_verifier::{
    compute_commitment, compute_storage_commitment,
    measurement::{
        compute_fork_url_hash, parse_katana_cmdline, verify_measurement, MeasurementConstants,
    },
    stub::VerifierInput,
    verify_attestation, verify_contracts_proof, verify_global_state_root, verify_storage_proof,
};

pub fn main() {
    entrypoint().unwrap()
}

/// Pre-computed measurement constants for the current build.
/// Generated by `snp-digest --checkpoint` on the OVMF/kernel/initrd build artifacts.
/// These MUST be hardcoded (not passed as input) so the operator cannot fake them.
///
/// TODO: Replace with actual values from `snp-digest --checkpoint`.
fn measurement_constants() -> MeasurementConstants {
    MeasurementConstants {
        intermediate_ld: [0u8; 48], // SHA-384 state after OVMF + metadata
        kernel_sha256: [0u8; 32],   // SHA-256(kernel binary)
        initrd_sha256: [0u8; 32],   // SHA-256(initrd binary)
        hashes_page_gpa: 0x800000,  // GPA from OVMF metadata
        hashes_table_offset: 0,     // Offset within the page
        vmsa_pages: vec![[0u8; 4096]], // VMSA content (1 vCPU)
    }
}

pub fn entrypoint() -> anyhow::Result<()> {
    let input = sp1_zkvm::io::read_vec();
    let verifier_input = VerifierInput::decode(&input)?;

    // Step 1: Verify TEE attestation (report signature, certificates, etc.)
    let mut output = verify_attestation(verifier_input.clone())?;

    // Step 1.5: Verify measurement matches kernel cmdline (if provided)
    if !verifier_input.kernelCmdline.is_empty() {
        // Extract measurement from raw attestation report (offset 0x90, 48 bytes)
        let mut expected_measurement = [0u8; 48];
        expected_measurement.copy_from_slice(&verifier_input.rawReport[0x90..0xC0]);

        let constants = measurement_constants();
        verify_measurement(&constants, &verifier_input.kernelCmdline, &expected_measurement)?;

        // Measurement verified - write to journal output
        output.measurement = Bytes::copy_from_slice(&expected_measurement);

        // Parse fork parameters from cmdline
        let fork_params = parse_katana_cmdline(&verifier_input.kernelCmdline);
        if let Some(block) = fork_params.fork_block {
            output.forkBlock = block;
        }
        if let Some(ref url) = fork_params.fork_url {
            output.forkUrlHash = B256::from_slice(&compute_fork_url_hash(url));
        }
    }

    // Steps 2-4: Full state verification (only if storage keys provided)
    if !verifier_input.storageKeys.is_empty() {
        // Step 2: Verify global_state_root = hash("STARKNET_STATE_V0", contracts_tree_root, classes_tree_root)
        // This proves that contracts_tree_root is part of the attested state
        verify_global_state_root(
            &verifier_input.globalStateRoot.0,
            &verifier_input.contractsTreeRoot.0,
            &verifier_input.classesTreeRoot.0,
        )?;

        // Step 3: Verify contract is in contracts_tree with expected storage_root
        // This proves that contractStorageRoot belongs to contractAddress in the attested state
        verify_contracts_proof(
            &verifier_input.contractsTreeRoot.0,
            &verifier_input.contractAddress.0,
            &verifier_input.contractClassHash.0,
            &verifier_input.contractStorageRoot.0,
            verifier_input.contractLeafNonce,
            &verifier_input.contractsProofNodes,
        )?;

        // Step 4: Verify storage keys/values are in contract's storage trie
        // This proves that keys/values are part of the contract's storage
        verify_storage_proof(
            &verifier_input.contractStorageRoot.0,
            &verifier_input.storageKeys,
            &verifier_input.storageValues,
            &verifier_input.storageProofNodes,
        )?;

        // Step 5: Compute commitment using global_state_root (the attested root)
        let storage_commitment = compute_storage_commitment(
            &verifier_input.storageKeys,
            &verifier_input.storageValues,
        );
        let commitment = compute_commitment(
            &storage_commitment,
            &verifier_input.contractAddress.0,
            verifier_input.nonce,
            &verifier_input.globalStateRoot.0, // Use global_state_root (attested)
        );
        output.storageCommitment = B256::from_slice(&commitment.to_bytes_be());
    }

    sp1_zkvm::io::commit_slice(&output.encode());
    Ok(())
}
